apiVersion: v1
kind: Secret
metadata:
  name: superset-t4dsuperset-env  ## superset-{{ Values.nameOverride }}-env
  namespace: t4dsuperset-superset
type: Opaque
stringData:
  # database
  DB_HOST: host.docker.internal
  DB_NAME: testing_kindsuperset
  DB_PASS: testing_kindsuperset
  DB_PORT: "5432"
  DB_USER: testing_kindsuperset
  SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://testing_kindsuperset:testing_kindsuperset@host.docker.internal:5432/testing_kindsuperset

  # app
  SUPERSET_SECRET_KEY: "somerandomkey"
  APPLICATION_HOST: "t4dsuperset.dalgo.org"

  # redis
  REDIS_CELERY_DB: "0"
  REDIS_DB: "1"
  REDIS_HOST: "t4dsuperset-redis-headless" ## "{{ .Release.Name }}-redis-headless"
  REDIS_PORT: "6379"
  REDIS_PROTO: redis
  REDIS_USER: ""

  # google oauth
  ENABLE_OAUTH: 
  GOOGLE_CLIENT_ID:
  GOOGLE_CLIENT_SECRET:
  GOOGLE_WHITELISTED_DOMAIN: